print("----------------------------------")
print("Welcome to my Calculator")
print("----------------------------------")
print("Enter your 1st number ")
a=input()
print("Enter your 2nd number ")
b=input()
print("Congratulations!!")
print("Your answer is",int(a)+int(b))